llm:
  provider: openai
  model: gpt-4
  api_key_env_var: OPENAI_API_KEY

evolution:
  population_size: 3
  generations: 2
  temperature: 0.8
  top_k: 1
  mutate_top_k: 2
  crossover_top_k: 1

evaluation:
  maximize: auc
